name:                HUnit-unicode
version:             0.1.0.0
github:              "natsuki14/HUnit-unicode"
license:             PublicDomain
author:              Natsuki Kawai
maintainer:          kawai@charon.tech

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category: Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natsuki14/HUnit-unicode#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit
- unicode-show

ghc-options:
- -Wno-tabs

library:
  source-dirs: src
